# Generated by Django 3.2.3 on 2021-05-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VidPens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvidp', models.CharField(max_length=35, verbose_name='Вид пенсии')),
            ],
            options={
                'verbose_name': 'Вид пенсии',
                'verbose_name_plural': 'Виды пенсий',
                'ordering': ['nvidp'],
            },
        ),
        migrations.CreateModel(
            name='Pd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.IntegerField(verbose_name='Номер дела')),
                ('snils', models.CharField(max_length=14, verbose_name='СНИЛС')),
                ('fam', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('fname', models.CharField(max_length=25, verbose_name='Отчество')),
                ('dr', models.DateField(verbose_name='Дата рождения')),
                ('zind', models.CharField(max_length=6, verbose_name='Индекс')),
                ('gor', models.CharField(max_length=25, verbose_name='Город')),
                ('ul', models.CharField(max_length=25, verbose_name='Улица')),
                ('dom', models.CharField(max_length=8, verbose_name='Дом')),
                ('kor', models.CharField(max_length=2, verbose_name='Корпус')),
                ('kvar', models.CharField(max_length=4, verbose_name='Квартира')),
                ('dnp', models.DateField(verbose_name='Дата назначения пенсии')),
                ('dlp', models.DateField(verbose_name='Дата прекращения выплаты')),
                ('dhp', models.DateField(verbose_name='Дата хранения')),
                ('drr', models.DateField(verbose_name='Дата ревизии')),
                ('post', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('link', models.CharField(max_length=8, verbose_name='Линк')),
                ('ds', models.DateField(verbose_name='Дата смерти')),
                ('sud', models.CharField(max_length=1, verbose_name='Линк СУД')),
                ('nud', models.IntegerField(verbose_name='Номер Uдела')),
                ('nvidp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pdarxiv.vidpens', verbose_name='Вид пенсии')),
            ],
            options={
                'verbose_name': 'Архивное дело',
                'verbose_name_plural': 'Архивные дела',
                'ordering': ['nom'],
            },
        ),
    ]
