# Generated by Django 3.2.3 on 2021-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='kor',
            field=models.CharField(max_length=2, null=True, verbose_name='Корпус'),
        ),
    ]
