# Generated by Django 3.2.3 on 2021-05-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0002_alter_pd_kor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='drr',
            field=models.DateField(blank=True, verbose_name='Дата ревизии'),
        ),
        migrations.AlterField(
            model_name='pd',
            name='ds',
            field=models.DateField(blank=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='pd',
            name='fname',
            field=models.CharField(blank=True, max_length=25, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='pd',
            name='kor',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='pd',
            name='kvar',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Квартира'),
        ),
    ]
