# Generated by Django 3.2.3 on 2021-05-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0003_auto_20210517_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='nom',
            field=models.IntegerField(unique=True, verbose_name='Номер дела'),
        ),
    ]
