# Generated by Django 3.2.3 on 2021-07-14 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0005_auto_20210519_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncatp', models.CharField(max_length=35, verbose_name='Категория получателя')),
            ],
            options={
                'verbose_name': 'Категория получателя',
                'verbose_name_plural': 'Категории получателя',
                'ordering': ['ncatp'],
            },
        ),
        migrations.AlterModelOptions(
            name='pd',
            options={'ordering': ['fam', 'name', 'fname'], 'verbose_name': 'Архивное дело', 'verbose_name_plural': 'Архивные дела'},
        ),
        migrations.AlterField(
            model_name='pd',
            name='dhp',
            field=models.DateField(verbose_name='Дата хранения ПО'),
        ),
        migrations.AlterField(
            model_name='pd',
            name='link',
            field=models.CharField(max_length=80, verbose_name='Категории умершего'),
        ),
        migrations.AlterField(
            model_name='pd',
            name='nud',
            field=models.IntegerField(verbose_name='Номер удостоверения'),
        ),
        migrations.AlterField(
            model_name='pd',
            name='snils',
            field=models.CharField(error_messages={'invalid': 'Формат СНИЛС д.б. 123-456-789 10'}, max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\d{3}-\\d{3}-\\d{3} \\d{2}$')], verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='pd',
            name='sud',
            field=models.CharField(max_length=4, verbose_name='Серия удостоверения'),
        ),
        migrations.AddIndex(
            model_name='pd',
            index=models.Index(fields=['nom'], name='ord_by_nom'),
        ),
        migrations.AddIndex(
            model_name='pd',
            index=models.Index(fields=['fam', 'name', 'fname'], name='ord_by_fio'),
        ),
    ]
