# Generated by Django 3.2.3 on 2021-07-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0006_auto_20210714_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='pd',
            name='catp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pdarxiv.catpens', verbose_name='Категория1 умершего'),
        ),
    ]
