# Generated by Django 3.2.3 on 2021-07-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0008_pd_link2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pd',
            old_name='catp',
            new_name='link1',
        ),
    ]
