# Generated by Django 3.2.3 on 2021-07-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0009_rename_catp_pd_link1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catpens',
            name='ncatp',
            field=models.CharField(max_length=45, verbose_name='Категория получателя'),
        ),
    ]
