# Generated by Django 3.2.3 on 2021-07-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0010_alter_catpens_ncatp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catpens',
            options={'ordering': ['id'], 'verbose_name': 'Категория получателя', 'verbose_name_plural': 'Категории получателя'},
        ),
        migrations.AddField(
            model_name='pd',
            name='link3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catp2', to='pdarxiv.catpens', verbose_name='Категория3 умершего'),
        ),
    ]
