# Generated by Django 3.2.3 on 2021-07-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0013_auto_20210714_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='link',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Категории умершего'),
        ),
    ]
