# Generated by Django 3.2.3 on 2021-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0014_alter_pd_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='nud',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер удостоверения'),
        ),
        migrations.AlterField(
            model_name='pd',
            name='sud',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия удостоверения'),
        ),
    ]
