# Generated by Django 3.2.3 on 2021-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0015_auto_20210722_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='nom',
            field=models.IntegerField(error_messages={'invalid': 'Формат СНИЛС д.б. 123-456-789 10'}, unique=True, verbose_name='Номер дела'),
        ),
    ]
