# Generated by Django 3.2.3 on 2021-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0016_alter_pd_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='nom',
            field=models.IntegerField(unique=True, verbose_name='Номер дела'),
        ),
    ]
