# Generated by Django 3.2.3 on 2021-11-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0017_alter_pd_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocNsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Населенный пункт')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VocUlc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Улица')),
                ('kodnsp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pdarxiv.vocnsp', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'ordering': ['kodnsp', 'name'],
            },
        ),
    ]
