# Generated by Django 3.2.3 on 2021-11-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0019_alter_pd_gor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='ul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pdarxiv.voculc', verbose_name='Улица'),
        ),
    ]
