# Generated by Django 3.2.3 on 2021-11-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0020_alter_pd_ul'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koddistrict', models.CharField(max_length=4, verbose_name='Код Района')),
                ('namedistrict', models.CharField(max_length=55, verbose_name='Наименование Района')),
            ],
            options={
                'verbose_name': 'Код Района',
                'verbose_name_plural': 'Коды Районов',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='vidpens',
            options={'ordering': ['id'], 'verbose_name': 'Вид пенсии', 'verbose_name_plural': 'Виды пенсий'},
        ),
    ]
