# Generated by Django 3.2.3 on 2021-11-22 13:55
from datetime import datetime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdarxiv', '0021_auto_20211122_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='pd',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pd',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AddField(
            model_name='pd',
            name='user_create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_create', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pd',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_update', to=settings.AUTH_USER_MODEL, verbose_name='пользователь отредактировал'),
        ),
    ]
