# Generated by Django 3.2.3 on 2021-11-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdarxiv', '0023_auto_20211122_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pd',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
