# Generated by Django 3.2.3 on 2021-11-23 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdarxiv', '0024_auto_20211122_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd',
            name='user_create',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_create', to='auth.user'),
            preserve_default=False,
        ),
    ]
