# Generated by Django 3.2.3 on 2021-12-22 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdarxiv', '0026_auto_20211220_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='pd',
            name='user_create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pd',
            name='user_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_update', to=settings.AUTH_USER_MODEL, verbose_name='пользователь отредактировал'),
        ),
    ]
