# Generated by Django 3.2.3 on 2021-12-23 13:45

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdarxiv', '0027_auto_20211222_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='pd',
            name='fuser_create',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuser_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pd',
            name='fuser_update',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='fuser_update', to=settings.AUTH_USER_MODEL),
        ),
    ]
